apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:   #  is important if you want your application can get the traffic from service 
   x: hello  # label always be in key: value pair and it must be unique 
  name: pod1  # must be unique
spec:
  containers:
  - image: dockerashu/alpine:entry
    name: pod1
    command: ["/bin/sh","-c","ping 8.8.8.8"]   #  command can replace entrypoint parent process in Docker img
